

export interface User {
  id: string;
  name: string;
  role: 'student' | 'admin';
  profile?: string;
  dob?: string;
  branch?: string;
  year?: string;
  university?: string;
  degree?: string;
  cgpa?: string;
  email?: string;
  phone?: string;
  skills?: string[];
  avatarUrl?: string;
}

export type ActivityCategory =
  | 'Internship'
  | 'Certification'
  | 'Volunteering'
  | 'Workshop'
  | 'Leadership'
  | 'Competition'
  | 'Community Service'
  | 'Conference';

export interface Activity {
  id: string;
  studentId: string;
  studentName: string;
  title: string;
  category: ActivityCategory;
  date: string; // ISO 8601 format
  description: string;
  status: 'Approved' | 'Pending' | 'Rejected';
  // Detailed fields
  organization?: string; // For internships, volunteering, clubs
  role?: string; // For leadership, internships
  duration?: string; // For internships, leadership, volunteering
  provider?: string; // For certifications
  achievement?: 'Winner' | 'Finalist' | 'Participant'; // For competitions
  impact?: string; // For community service
}

const students: User[] = [
  {
    id: 'user-1',
    name: 'Yash Pawar',
    role: 'student',
    email: 'yash.pawar@example.com',
    profile: `Yash Pawar is a second-year Information Technology student with a keen interest in cloud computing and DevOps. He has hands-on experience with AWS and Docker, and is actively looking for internships in the cloud engineering space.`,
    dob: '2003-04-10',
    branch: 'Information Technology',
    year: '2nd Year',
    university: 'National Institute of Technology',
    degree: 'Bachelor of Technology',
    cgpa: '8.8',
    skills: ['AWS', 'Docker', 'Python', 'CI/CD'],
  },
  {
    id: 'user-2',
    name: 'Aditi Singh',
    role: 'student',
    email: 'aditi.singh@example.com',
    profile: 'Aditi is a third-year Computer Science student passionate about competitive programming and data structures. She is a 5-star coder on CodeChef.',
    dob: '2002-09-22',
    branch: 'Computer Science',
    year: '3rd Year',
    university: 'Indian Institute of Technology',
    degree: 'Bachelor of Technology',
    cgpa: '9.2',
    skills: ['C++', 'Algorithms', 'Data Structures', 'Java'],
  },
  {
    id: 'user-3',
    name: 'Vikram Patel',
    role: 'student',
    email: 'vikram.patel@example.com',
    profile: 'Vikram is a final-year Mechanical Engineering student with a focus on automotive design and CAD modeling.',
    dob: '2001-07-15',
    branch: 'Mechanical Engineering',
    year: '4th Year',
    university: 'National Institute of Technology',
    degree: 'Bachelor of Engineering',
    cgpa: '8.5',
    skills: ['AutoCAD', 'SolidWorks', 'Thermodynamics'],
  },
  {
    id: 'user-4',
    name: 'Priya Kumar',
    role: 'student',
    email: 'priya.kumar@example.com',
    profile: 'Priya is a first-year Civil Engineering student, enthusiastic about sustainable infrastructure and urban planning.',
    dob: '2004-11-05',
    branch: 'Civil Engineering',
    year: '1st Year',
    university: 'Indian Institute of Technology',
    degree: 'Bachelor of Engineering',
    cgpa: '9.0',
    skills: ['Surveying', 'Structural Analysis', 'Green Building'],
  },
  {
    id: 'user-5',
    name: 'Rohan Gupta',
    role: 'student',
    email: 'rohan.gupta@example.com',
    profile: 'Rohan is a second-year Electrical Engineering student, interested in IoT and embedded systems.',
    dob: '2003-01-30',
    branch: 'Electrical Engineering',
    year: '2nd Year',
    university: 'National Institute of Technology',
    degree: 'Bachelor of Engineering',
    cgpa: '8.4',
    skills: ['Arduino', 'Raspberry Pi', 'C', 'VHDL'],
  },
  {
    id: 'user-6',
    name: 'Saanvi Reddy',
    role: 'student',
    email: 'saanvi.reddy@example.com',
    profile: 'Saanvi is a third-year IT student specializing in cybersecurity and network administration.',
    dob: '2002-06-18',
    branch: 'Information Technology',
    year: '3rd Year',
    university: 'Indian Institute of Technology',
    degree: 'Bachelor of Technology',
    cgpa: '9.5',
    skills: ['Ethical Hacking', 'Networking', 'Linux', 'Cryptography'],
  },
  {
    id: 'user-7',
    name: 'Kabir Mehta',
    role: 'student',
    email: 'kabir.mehta@example.com',
    profile: 'A first-year Computer Science student exploring the world of web development and mobile apps.',
    dob: '2004-03-12',
    branch: 'Computer Science',
    year: '1st Year',
    university: 'National Institute of Technology',
    degree: 'Bachelor of Technology',
    cgpa: '8.9',
    skills: ['HTML', 'CSS', 'JavaScript', 'React Native'],
  },
  {
    id: 'user-8',
    name: 'Diya Joshi',
    role: 'student',
    email: 'diya.joshi@example.com',
    profile: 'Diya is a second-year Mechanical student with a passion for 3D printing and rapid prototyping.',
    dob: '2003-10-02',
    branch: 'Mechanical Engineering',
    year: '2nd Year',
    university: 'Indian Institute of Technology',
    degree: 'Bachelor of Engineering',
    cgpa: '8.7',
    skills: ['3D Printing', 'Fusion 360', 'Prototyping'],
  },
  {
    id: 'user-9',
    name: 'Arjun Nair',
    role: 'student',
    email: 'arjun.nair@example.com',
    profile: 'A final-year Civil Engineering student focusing on transportation engineering and smart cities.',
    dob: '2001-05-25',
    branch: 'Civil Engineering',
    year: '4th Year',
    university: 'National Institute of Technology',
    degree: 'Bachelor of Engineering',
    cgpa: '8.1',
    skills: ['Traffic Simulation', 'GIS', 'Urban Planning'],
  },
  {
    id: 'user-10',
    name: 'Myra Das',
    role: 'student',
    email: 'myra.das@example.com',
    profile: 'Myra is a third-year Electrical Engineering student specializing in renewable energy systems.',
    dob: '2002-12-11',
    branch: 'Electrical Engineering',
    year: '3rd Year',
    university: 'Indian Institute of Technology',
    degree: 'Bachelor of Engineering',
    cgpa: '9.3',
    skills: ['Solar Power', 'Wind Energy', 'MATLAB'],
  },
  {
    id: 'user-11',
    name: 'Ishaan Khan',
    role: 'student',
    email: 'ishaan.khan@example.com',
    profile: 'A first-year Information Technology student, excited about data science and machine learning.',
    dob: '2004-08-08',
    branch: 'Information Technology',
    year: '1st Year',
    university: 'National Institute of Technology',
    degree: 'Bachelor of Technology',
    cgpa: '9.1',
    skills: ['Python', 'SQL', 'Data Analysis'],
  },
  {
    id: 'user-12',
    name: 'Ananya Verma',
    role: 'student',
    email: 'ananya.verma@example.com',
    profile: 'A final-year Computer Science student with expertise in full-stack development and cloud deployment.',
    dob: '2001-02-28',
    branch: 'Computer Science',
    year: '4th Year',
    university: 'Indian Institute of Technology',
    degree: 'Bachelor of Technology',
    cgpa: '9.6',
    skills: ['React', 'Node.js', 'MongoDB', 'GCP'],
  },
  {
    id: 'user-13',
    name: 'Vivaan Iyer',
    role: 'student',
    email: 'vivaan.iyer@example.com',
    profile: 'Vivaan is a third-year Mechanical Engineering student interested in fluid mechanics and aerodynamics.',
    dob: '2002-04-14',
    branch: 'Mechanical Engineering',
    year: '3rd Year',
    university: 'National Institute of Technology',
    degree: 'Bachelor of Engineering',
    cgpa: '8.6',
    skills: ['CFD', 'Ansys', 'Aerodynamics'],
  },
  {
    id: 'user-14',
    name: 'Zara Ali',
    role: 'student',
    email: 'zara.ali@example.com',
    profile: 'Zara is a second-year Civil Engineering student focusing on environmental engineering and water resource management.',
    dob: '2003-11-20',
    branch: 'Civil Engineering',
    year: '2nd Year',
    university: 'Indian Institute of Technology',
    degree: 'Bachelor of Engineering',
    cgpa: '8.9',
    skills: ['Water Quality Testing', 'Environmental Impact Assessment'],
  },
  {
    id: 'user-15',
    name: 'Reyansh Shah',
    role: 'student',
    email: 'reyansh.shah@example.com',
    profile: 'A first-year Electrical Engineering student exploring signal processing and communication systems.',
    dob: '2004-01-01',
    branch: 'Electrical Engineering',
    year: '1st Year',
    university: 'National Institute of Technology',
    degree: 'Bachelor of Engineering',
    cgpa: '9.4',
    skills: ['Signal Processing', 'Digital Communication', 'C++'],
  },
  {
    id: 'user-16',
    name: 'Aryan Sharma',
    role: 'student',
    email: 'aryan.sharma@example.com',
    profile: 'A second-year Instrumentation Engineering student focused on process control and automation.',
    dob: '2003-05-19',
    branch: 'Instrumentation',
    year: '2nd Year',
    university: 'Indian Institute of Technology',
    degree: 'Bachelor of Engineering',
    cgpa: '8.8',
    skills: ['PLC', 'SCADA', 'Industrial Automation'],
  },
  {
    id: 'user-17',
    name: 'Kiara Desai',
    role: 'student',
    email: 'kiara.desai@example.com',
    profile: 'A fourth-year ENTC student specializing in wireless communication and RF engineering.',
    dob: '2001-09-03',
    branch: 'ENTC',
    year: '4th Year',
    university: 'National Institute of Technology',
    degree: 'Bachelor of Engineering',
    cgpa: '9.1',
    skills: ['RF Design', '5G Technology', 'Antenna Theory'],
  },
];

const admin: User = {
  id: 'admin-1',
  name: 'Mr. Pawar',
  role: 'admin',
  email: 'pawar@example.com',
};

export const mockUsers: { student: User; admin: User, all: User[] } = {
  student: students[0],
  admin: admin,
  all: [...students, admin]
};

export const mockActivities: Activity[] = [
  {
    id: 'activity-1',
    studentId: 'user-1',
    studentName: 'Yash Pawar',
    title: 'AWS Cloud Practitioner',
    category: 'Certification',
    date: '2023-10-15',
    provider: 'Amazon Web Services',
    description: 'Validated foundational understanding of AWS Cloud services.',
    status: 'Approved',
  },
  {
    id: 'activity-2',
    studentId: 'user-2',
    studentName: 'Aditi Singh',
    title: 'Google Kick Start - Rank 50',
    category: 'Competition',
    date: '2024-03-10',
    organization: 'Google',
    achievement: 'Finalist',
    description: 'Secured a global rank of 50 in the competitive programming contest.',
    status: 'Approved',
  },
  {
    id: 'activity-3',
    studentId: 'user-3',
    studentName: 'Vikram Patel',
    title: 'Intern at Tata Motors',
    category: 'Internship',
    date: '2023-06-01',
    organization: 'Tata Motors',
    role: 'Design Intern',
    duration: '6 months',
    description: 'Worked on the chassis design for a new electric vehicle model.',
    status: 'Approved',
  },
  {
    id: 'activity-4',
    studentId: 'user-1',
    studentName: 'Yash Pawar',
    title: 'DevOps Workshop Facilitator',
    category: 'Leadership',
    date: '2024-02-20',
    organization: 'University Tech Club',
    description: 'Led a workshop on CI/CD pipelines for over 50 students.',
    status: 'Approved',
  },
  {
    id: 'activity-5',
    studentId: 'user-6',
    studentName: 'Saanvi Reddy',
    title: 'Certified Ethical Hacker (CEH)',
    category: 'Certification',
    date: '2024-01-05',
    provider: 'EC-Council',
    description: 'Achieved certification in ethical hacking and penetration testing.',
    status: 'Approved',
  },
  {
    id: 'activity-6',
    studentId: 'user-7',
    studentName: 'Kabir Mehta',
    title: 'Clean Up Drive',
    category: 'Community Service',
    date: '2023-11-25',
    impact: 'Collected over 50kg of waste from the local beach.',
    description: 'Participated in a city-wide beach clean-up drive.',
    status: 'Approved',
  },
  {
    id: 'activity-7',
    studentId: 'user-10',
    studentName: 'Myra Das',
    title: 'Solar Car Project',
    category: 'Workshop',
    date: '2023-09-15',
    organization: 'Renewable Energy Club',
    description: 'Participated in a month-long workshop to build a functional solar-powered car.',
    status: 'Approved',
  },
  {
    id: 'activity-8',
    studentId: 'user-12',
    studentName: 'Ananya Verma',
    title: 'Head of Student Council',
    category: 'Leadership',
    date: '2023-08-01',
    organization: 'University Student Council',
    duration: '1 Year',
    description: 'Elected as the Head of the Student Council for the academic year.',
    status: 'Approved',
  },
  {
    id: 'activity-9',
    studentId: 'user-2',
    studentName: 'Aditi Singh',
    title: 'Summer Intern at Microsoft',
    category: 'Internship',
    date: '2024-05-20',
    organization: 'Microsoft',
    role: 'Software Development Intern',
    duration: '3 months',
    description: 'Working on optimizing backend services for Microsoft Teams.',
    status: 'Pending',
  },
  {
    id: 'activity-10',
    studentId: 'user-14',
    studentName: 'Zara Ali',
    title: 'National Environmental Conference',
    category: 'Conference',
    date: '2024-04-18',
    organization: 'Ministry of Environment',
    description: 'Presented a paper on rainwater harvesting techniques.',
    status: 'Approved',
  },
  {
    id: 'activity-11',
    studentId: 'user-5',
    studentName: 'Rohan Gupta',
    title: 'IoT for Smart Homes',
    category: 'Workshop',
    date: '2024-03-05',
    organization: 'IEEE Student Chapter',
    description: 'A hands-on workshop building smart home devices using Arduino and ESP32.',
    status: 'Approved',
  },
  {
    id: 'activity-12',
    studentId: 'user-8',
    studentName: 'Diya Joshi',
    title: 'RoboWars Competition',
    category: 'Competition',
    date: '2024-02-12',
    organization: 'TechFest IIT Bombay',
    achievement: 'Finalist',
    description: 'Built a combat robot that reached the final round of the competition.',
    status: 'Approved',
  },
  {
    id: 'activity-13',
    studentId: 'user-4',
    studentName: 'Priya Kumar',
    title: 'AutoCAD for Beginners',
    category: 'Certification',
    date: '2023-12-20',
    provider: 'Autodesk',
    description: 'Completed the certified user course for AutoCAD.',
    status: 'Approved',
  },
  {
    id: 'activity-14',
    studentId: 'user-11',
    studentName: 'Ishaan Khan',
    title: 'Blood Donation Camp',
    category: 'Volunteering',
    date: '2024-01-26',
    organization: 'Red Cross Society',
    description: 'Volunteered to manage registrations at the annual blood donation camp.',
    status: 'Rejected',
  },
   {
    id: 'activity-15',
    studentId: 'user-1',
    studentName: 'Yash Pawar',
    title: 'Open Source Contribution',
    category: 'Volunteering',
    date: '2024-05-10',
    organization: 'The Odin Project',
    description: 'Contributed documentation fixes to a popular open-source curriculum.',
    status: 'Pending',
  },
  {
    id: 'activity-16',
    studentId: 'user-4',
    studentName: 'Priya Kumar',
    title: 'Bridge Design Competition',
    category: 'Competition',
    date: '2024-04-02',
    organization: 'ASCE Student Chapter',
    achievement: 'Participant',
    description: 'Submitted a design for the annual bridge building competition. Did not qualify for the final round due to a calculation error in the load-bearing capacity.',
    status: 'Rejected',
  },
  {
    id: 'activity-17',
    studentId: 'user-5',
    studentName: 'Rohan Gupta',
    title: 'Paper Presentation on IoT',
    category: 'Conference',
    date: '2024-03-20',
    organization: 'University Tech Symposium',
    description: 'Submitted a paper on IoT applications. The paper was rejected as it did not meet the formatting guidelines.',
    status: 'Rejected',
  },
  {
    id: 'activity-18',
    studentId: 'user-9',
    studentName: 'Arjun Nair',
    title: 'Smart City Hackathon',
    category: 'Competition',
    date: '2024-04-10',
    organization: 'Smart India Hackathon',
    achievement: 'Participant',
    description: 'Participated in the hackathon but the project was not selected for the final round. Submission was incomplete.',
    status: 'Rejected',
  },
  {
    id: 'activity-19',
    studentId: 'user-13',
    studentName: 'Vivaan Iyer',
    title: 'CFD Workshop',
    category: 'Workshop',
    date: '2024-01-15',
    organization: 'Mechanical Engineering Association',
    description: 'Application was rejected due to prerequisite courses not being completed.',
    status: 'Rejected',
  },
  {
    id: 'activity-20',
    studentId: 'user-15',
    studentName: 'Reyansh Shah',
    title: 'Circuit Design Contest',
    category: 'Competition',
    date: '2024-02-28',
    organization: 'IEEE Student Chapter',
    achievement: 'Participant',
    description: 'The submission was disqualified due to late entry.',
    status: 'Rejected',
  },
];

    

    

    



